<h1 class="page_title beta">Welcome to wwhypda</h1><div id="beta"></div>
<p><b>The world wide catalog of hydrogeological properties of earth materials.</b></p>
<p>This project was originaly launched in 2006 to help hydrogeologists or reservoir engineers
for the characterization of underground reservoirs with respect to their flow and transport
properties by providing a catalogue of typical values, or typical statistical distributions
of physical properties of rock types.</p>
<p>The application is currently being rewritten to facilitate data query and editing.</p>
<div class="gallery">
<a href="/images/raw_data.png" rel="lightbox"><img src="/images/thumbs/raw_data.jpg"/></a>
<a href="/images/statistics.png" rel="lightbox"><img src="/images/thumbs/statistics.jpg"/></a>
<a href="/images/inline_edit.png" rel="lightbox"><img src="/images/thumbs/inline_edit.jpg"/></a>
<a href="/images/contribute_step1.png" rel="lightbox"><img src="/images/thumbs/contribute_step1.jpg"/></a>
<a href="/images/contribute_step2.png" rel="lightbox"><img src="/images/thumbs/contribute_step2.jpg"/></a>
<a href="/images/contribute_step3.png" rel="lightbox"><img src="/images/thumbs/contribute_step3.jpg"/></a>
<a href="/images/contribute_step4.png" rel="lightbox"><img src="/images/thumbs/contribute_step4.jpg"/></a>
</div>